Release Dangerzone 0.4.2
freedomofpress/apt-tools-prod pull request #8
Opened 2023-08-07 14:50 UTC by apyrgio

This PR introduces the following changes in the APT repo:

1. Remove Dangerzone 0.4.1 debs
2. Add Dangerzone 0.4.2 debs
3. Remove the Ubuntu Kinetic Kudu repo
4. Add the Debian Trixie and Ubuntu Lunar Lobster repos

2023-08-07 18:15 UTC, deeplow approved these changes

2023-08-08 11:59 UTC, deeplow requested changes
I only see two GIT LFS objects, shouldn't there be at least 4?

2023-08-08 14:22 UTC, apyrgio commented
Actually, there should be at least `no. of platforms` x 2 = 12 Git LFS objects. We have chosen not to go that way for two reasons:

1. Creating an object per platform takes a lot of time, storage space, and bandwidth.
2. `reprepro` has an issue whereby a file with the same name across platforms cannot have different hash.

So, we use symlinks instead, which brings down the number of LFS objects to 2. See also this PR https://github.com/freedomofpress/dangerzone/pull/322

2023-08-08 14:24 UTC, deeplow commented
Ah. OK. That explains it. It wasn't immediately obvious on the github interface.

2023-08-08 15:34 UTC, merged